version: '3.8'

services:
  challenge:
    build: .
    container_name: linear_model_challenge
    ports:
      - "1337:1337"
    restart: unless-stopped
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - chal_network

networks:
  chal_network:
    driver: bridge
