#!/usr/bin/env python3

import os

print("I am code runner 1.0")
code = input("give me code to run: ")
cells = [0] * 0x100
pointer = 0
cmd = ""
for i in range(len(code)):
    if code[i] == ">":
        pointer = (pointer + 1) % 0x100
    elif code[i] == "<":
        pointer = (pointer - 1) % 0x100
    elif code[i] == "+":
        cells[pointer] = (cells[pointer] + 1) % 0x100
    elif code[i] == "-":
        cells[pointer] = (cells[pointer] - 1) % 0x100
    elif code[i] == "!":
        cmd += chr(cells[pointer])
    elif code[i] == "$":
        # run the command!!!
        os.system(cmd)
        cmd = ""
print("did you get the flag???")
