# Use the official PHP image from the Docker Hub
FROM php:8.2-apache

COPY ./challenge/* /var/www/html/

RUN echo "\nAlphabit{u_sill_b4by_f0r_m3_until_us0lveit}" >> /etc/passwd


WORKDIR /var/www/html